/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedEnquiriesRouteImport } from './routes/_authenticated/enquiries'
import { Route as AuthenticatedNewJobRouteImport } from './routes/_authenticated/new-job'
import { Route as AuthenticatedNewRepairRouteImport } from './routes/_authenticated/new-repair'
import { Route as AuthenticatedOutlookRouteImport } from './routes/_authenticated/outlook'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWorkshopRouteImport } from './routes/_authenticated/workshop'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients/$id'
import { Route as AuthenticatedEnquiriesIndexRouteImport } from './routes/_authenticated/enquiries/index'
import { Route as AuthenticatedEnquiriesIdRouteImport } from './routes/_authenticated/enquiries/$id'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices/$id'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedJobsRefRouteImport } from './routes/_authenticated/jobs/$ref'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnquiriesRoute = AuthenticatedEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewJobRoute = AuthenticatedNewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRepairRoute = AuthenticatedNewRepairRouteImport.update({
  id: '/new-repair',
  path: '/new-repair',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutlookRoute = AuthenticatedOutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkshopRoute = AuthenticatedWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnquiriesIndexRoute =
  AuthenticatedEnquiriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEnquiriesRoute,
  } as any)
const AuthenticatedEnquiriesIdRoute =
  AuthenticatedEnquiriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEnquiriesRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRefRoute = AuthenticatedJobsRefRouteImport.update({
  id: '/jobs/$ref',
  path: '/jobs/$ref',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/enquiries': typeof AuthenticatedEnquiriesRouteWithChildren
  '/new-job': typeof AuthenticatedNewJobRoute
  '/new-repair': typeof AuthenticatedNewRepairRoute
  '/outlook': typeof AuthenticatedOutlookRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workshop': typeof AuthenticatedWorkshopRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/jobs/$ref': typeof AuthenticatedJobsRefRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/new-job': typeof AuthenticatedNewJobRoute
  '/new-repair': typeof AuthenticatedNewRepairRoute
  '/outlook': typeof AuthenticatedOutlookRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workshop': typeof AuthenticatedWorkshopRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/jobs/$ref': typeof AuthenticatedJobsRefRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/enquiries': typeof AuthenticatedEnquiriesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/enquiries': typeof AuthenticatedEnquiriesRouteWithChildren
  '/_authenticated/new-job': typeof AuthenticatedNewJobRoute
  '/_authenticated/new-repair': typeof AuthenticatedNewRepairRoute
  '/_authenticated/outlook': typeof AuthenticatedOutlookRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workshop': typeof AuthenticatedWorkshopRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/jobs/$ref': typeof AuthenticatedJobsRefRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/enquiries'
    | '/new-job'
    | '/new-repair'
    | '/outlook'
    | '/reports'
    | '/settings'
    | '/workshop'
    | '/clients/$id'
    | '/enquiries/$id'
    | '/invoices/$id'
    | '/jobs/$ref'
    | '/clients/'
    | '/enquiries/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/new-job'
    | '/new-repair'
    | '/outlook'
    | '/reports'
    | '/settings'
    | '/workshop'
    | '/'
    | '/clients/$id'
    | '/enquiries/$id'
    | '/invoices/$id'
    | '/jobs/$ref'
    | '/clients'
    | '/enquiries'
    | '/jobs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/enquiries'
    | '/_authenticated/new-job'
    | '/_authenticated/new-repair'
    | '/_authenticated/outlook'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/workshop'
    | '/_authenticated/'
    | '/_authenticated/clients/$id'
    | '/_authenticated/enquiries/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/jobs/$ref'
    | '/_authenticated/clients/'
    | '/_authenticated/enquiries/'
    | '/_authenticated/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries': {
      id: '/_authenticated/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AuthenticatedEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-job': {
      id: '/_authenticated/new-job'
      path: '/new-job'
      fullPath: '/new-job'
      preLoaderRoute: typeof AuthenticatedNewJobRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-repair': {
      id: '/_authenticated/new-repair'
      path: '/new-repair'
      fullPath: '/new-repair'
      preLoaderRoute: typeof AuthenticatedNewRepairRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outlook': {
      id: '/_authenticated/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof AuthenticatedOutlookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop': {
      id: '/_authenticated/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof AuthenticatedWorkshopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries/': {
      id: '/_authenticated/enquiries/'
      path: '/'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof AuthenticatedEnquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedEnquiriesRoute
    }
    '/_authenticated/enquiries/$id': {
      id: '/_authenticated/enquiries/$id'
      path: '/$id'
      fullPath: '/enquiries/$id'
      preLoaderRoute: typeof AuthenticatedEnquiriesIdRouteImport
      parentRoute: typeof AuthenticatedEnquiriesRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$ref': {
      id: '/_authenticated/jobs/$ref'
      path: '/jobs/$ref'
      fullPath: '/jobs/$ref'
      preLoaderRoute: typeof AuthenticatedJobsRefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedEnquiriesRouteChildren {
  AuthenticatedEnquiriesIdRoute: typeof AuthenticatedEnquiriesIdRoute
  AuthenticatedEnquiriesIndexRoute: typeof AuthenticatedEnquiriesIndexRoute
}

const AuthenticatedEnquiriesRouteChildren: AuthenticatedEnquiriesRouteChildren =
  {
    AuthenticatedEnquiriesIdRoute: AuthenticatedEnquiriesIdRoute,
    AuthenticatedEnquiriesIndexRoute: AuthenticatedEnquiriesIndexRoute,
  }

const AuthenticatedEnquiriesRouteWithChildren =
  AuthenticatedEnquiriesRoute._addFileChildren(
    AuthenticatedEnquiriesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEnquiriesRoute: typeof AuthenticatedEnquiriesRouteWithChildren
  AuthenticatedNewJobRoute: typeof AuthenticatedNewJobRoute
  AuthenticatedNewRepairRoute: typeof AuthenticatedNewRepairRoute
  AuthenticatedOutlookRoute: typeof AuthenticatedOutlookRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkshopRoute: typeof AuthenticatedWorkshopRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedJobsRefRoute: typeof AuthenticatedJobsRefRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEnquiriesRoute: AuthenticatedEnquiriesRouteWithChildren,
  AuthenticatedNewJobRoute: AuthenticatedNewJobRoute,
  AuthenticatedNewRepairRoute: AuthenticatedNewRepairRoute,
  AuthenticatedOutlookRoute: AuthenticatedOutlookRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkshopRoute: AuthenticatedWorkshopRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedJobsRefRoute: AuthenticatedJobsRefRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
